//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoMusic
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiHat
    {
        public int id { get; set; }
        public string Song { get; set; }
        public string Singer { get; set; }
        public string Songwriter { get; set; }
        public string Album { get; set; }
    }
}
